version: '3.3'

services:
  myDb:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=juan
      - POSTGRES_PASSWORD=admin12345
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/libn/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=email@gmal.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
